channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=24.1.2
- pip:
  - mlflow==3.4.0
  - accelerate==1.10.1
  - cloudpickle==3.1.1
  - cryptography==43.0.3
  - dataproc-spark-connect==0.8.3
  - dill==0.3.8
  - etils==1.13.0
  - google-adk==1.14.1
  - google-cloud-bigquery-connection==1.18.3
  - google-cloud-bigquery-storage==2.33.1
  - google-cloud-datastore==2.21.0
  - google-cloud-firestore==2.21.0
  - google-cloud-functions==1.20.4
  - google-cloud-language==2.17.2
  - google-cloud-logging==3.12.1
  - google-cloud-translate==3.21.1
  - google-colab==1.0.0
  - google-generativeai==0.8.5
  - importlib-resources==6.5.2
  - jax-cuda12-plugin==0.5.3
  - jax==0.5.3
  - librosa==0.11.0
  - matplotlib==3.10.0
  - numpy==2.0.2
  - nvidia-cuda-nvcc-cu12==12.5.82
  - nvidia-ml-py==12.575.51
  - oauth2client==4.1.3
  - opencv-contrib-python==4.12.0.88
  - opencv-python-headless==4.12.0.88
  - opencv-python==4.12.0.88
  - pandas==2.2.2
  - pydot==3.0.4
  - pyopenssl==24.2.1
  - pysocks==1.7.1
  - python-snappy==0.7.3
  - scikit-learn==1.6.1
  - scipy==1.16.2
  - tblib==3.1.0
  - tensorflow==2.19.0
  - torch==2.8.0
  - torchao==0.10.0
  - torchvision==0.23.0
  - transformers==4.56.1
  - zstandard==0.25.0
name: mlflow-env
